language: scala

sudo: required

services:
- docker

jdk:
- oraclejdk8

addons:
  apt:
    packages:
    - oracle-java8-installer

jobs:
  include:
  - stage: test
    script: sbt V2_0/scripted *
  - stage: test
    script: sbt V2_1/scripted *
  - stage: test
    script: sbt V2_2/scripted *

deploy:
  provider: script
  script: sbt publish githubRelease
  on:
    tags: true
    branch: master

before_cache:
- find "$HOME/.ivy2/cache" -name "ivydata-*.properties" -print -delete
- find "$HOME/.sbt"        -name "*.lock"               -print -delete

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
