language: scala

sudo: required

services:
- docker

jdk:
- oraclejdk8

addons:
  apt:
    packages:
    - oracle-java8-installer

env:
  global:
  # PGP Passphrase
  - secure: "HqqiURe/e5wCWBeVbfTXRpiII+NG6jxPXecD0X+JQ3aNFN5mHCs3x7TupwYpqLGImZ6+eTWApiULMS1YJWVUnrcplMblXx5Oi5cwLqAAFwMcgjLyvpZU8CIsMdF3HqnYjkCSIAH11mYZ7otMnkP6OJ3qbpyfKg7mjgjb1c1jyE4EjdcxKCtRS/vMhoBBOv48PQyJAMoGAulmmUppZpp61aSMBVTd/vxbN8DNDGbxLgM/51+nfhC13Uw8Pid7WKaWOcwroc07pLCEFzvmuG0Rhf4STp557wpQ/udFHFKlKmaZRmbbvTExk/wC+L6rj6BvxosHJMZulSpAOCSDEOfiGU5fNzhp3tpqeM89CH+Mf+TIa0qxh+Xk9SJo0hT/amNEyHojkld6NAQoMJOyD/SdbLYLKoS1AJjpRqcUQo7FOgk2bN+iFi9eRJqUDWd7BzMQf9h/jkxcs9Sv/UpqmmbfaL1kBm1Bpd0ZXGf7ky7GHhje4c4mpW5taA7LSX7ylupGpBwFm2eYwLcETp0yTNLl7Gz2YrGxZb6iTP352OjXroniB8HUw6HiQ07oiAer87V6qcePkm2WzrC7okDq/LvuRuhNQ4ETXLJcgJG1xBYRydWi9gUyRcXeXw/HtiF4J/OqPyNAjCd18cdi+SPyxnLjlOl0DtbNVPbeh/KCHEoeCqU="
  # Bintray Username and API Key
  - BINTRAY_USER=steinybot
  - secure: "FO3uib+1urHS7grhZTW0ecOeBvzvHxMbeNY5p48AYlnXI+rwqF8sJntiRmb70tixi+2I+k+qO8Xhw/d7wSZroizuAAhbd04PkQ5Vil4mTRo6d85h/+RuEj6tW3MWjnI+ycBfdnV6BhHeZTI/obc0QKUIEDq+urQrMaMYsqAEn/BroHEZgGjvwFxU9oTNGu5DNi79QZxg9vudE0dQK3j446IdMY7KpiRXb4wvaopR2x2osu1iYeAVBcOycTkGygI2zbRBmxHBy9l4/nIfm6+/d1ztH5RUv3N2hszj1snLCOeNWbzHUsRmjiSUXZXFMqtBbYTa+hMh4lofHBva4qvf/Y4C7/2Q+kfMcY9fAEgAsf8vUuvhuhw72KG9CnlWeRr10WMXR1cl5DIu7c0GLBZkVXyGZ414iK70Eb/+nQgDdadrk17yRSdMfMNd1ch6hi8RbGIG1OVOENDMSn0m1J0I8iIvVJTo5t2d9yvvH5ztIGtPycLaDV6tZp8VEOKmxhOeUJL8DighLNJ755/FmoBAenwNc/jdTAnajUgbqno9zR6pM42UGWNGqFwiGeEFNUSrIEb5xPFvpaEczt/sZl8LzX7Nmj8phs52YkvaYtgxWZevxwafxq+YdxCDbXIfOsXNRWyahV5fpwOjvYZk5Hf990WObxscuBXjuyrfnzdygWQ="
  # Github Token
  - secure: "jPWZjfhoErQaOMmIher8LC3Dwv/2s9+VfJmg1DtCvESwUH7tJYdb65wvKUhU/FP9V1L6eiDiPlggR0x0FMy2E2TXPURBn4VrgrQt+Tm4ZrFMtgWZB7sOYzOnaqiViCZJvi60UigY81Cvj+QHi13PfbdKpBLFoKkEj1JA+/iezRszCkrrI5rvlZlnCw9QvZgF73I24D0gWuMFyPfD2dn8o/i25DQ6woI9yLQ0b+a3KeDEA2u6S6cUn/yM6jaauT9cnQgTG8ioViNoqIZ77IJzEGYOJ/0bP2a2qu+vEb9d4effcUu3Tc7fmtt8CdKTcmMeYL33MczOM0d7L3ila9sV5VxyTQSysXg+gAXIOyHs/GC9eS9xMxkfogPcajRo2TeAPMfo8TovUdCmVfJqcNyBZijy4Eu9kkMLlJWyMixKOiNAT0aOxgnM17bt/w9UtT3lrfLL73vD1UB43t+ICX1O/3d/I7G9sezcygOkuEnGxr0U94J6BOZ0vZV7mCOPFYpHDjfM75IFrjJv6U1BHHmEl8wgtbim3Hgx5d4GGFpqPMs7ndQ4pkSzQFsgQa6vAcZjo6E2CCMg+pzwwTif3B5bJplLz3fZjD+0aLfU1N79sYPSNHfgdQhwWfquUtipOXyibZm+R+cYYyy2EsYKxVgaID8v79dWZZs3KT9+lIoCUAs="

jobs:
  include:
  - stage: test
    script: sbt "V2_0/scripted *"
  - stage: test
    script: sbt "V2_1/scripted *"
  - stage: test
    script: sbt "V2_2/scripted *"

before_deploy:
- openssl aes-256-cbc -K $encrypted_4f7bbed6af32_key -iv $encrypted_4f7bbed6af32_iv -in key.asc.enc -out temp/target/.gnupg/key.asc -d

deploy:
  provider: script
  script: sbt publish githubRelease
  on:
    tags: true
    branch: master

before_cache:
- find "$HOME/.ivy2/cache" -name "ivydata-*.properties" -print -delete
- find "$HOME/.sbt"        -name "*.lock"               -print -delete

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
