language: scala

sudo: false

jdk:
- oraclejdk8

addons:
  apt:
    packages:
    - oracle-java8-installer

env:
  global:
  # PGP Passphrase
  #- secure: "ENCRYPTED_PGP_PASSPHRASE"
  # Bintray Username and API Key
  #- BINTRAY_USER=YOUR_BINTRAY_USER
  #- secure: "ENCRYPTED_BINTRAY_API_KEY"
  # GitHub Token
  #- secure: "ENCRYPTED_GITHUB_TOKEN"

script: sbt scripted

before_deploy:
#- openssl aes-256-cbc -K $encrypted_4a09436dfeda_key -iv $encrypted_4a09436dfeda_iv -in travis/secring.asc.enc -out travis/secring.asc -d

deploy:
  provider: script
  script: sbt publish githubRelease
  on:
    tags: true
    branch: master

before_cache:
- find "$HOME/.ivy2/cache" -name "ivydata-*.properties" -print -delete
- find "$HOME/.sbt"        -name "*.lock"               -print -delete

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
