#!/usr/bin/env bash

# The GnuPG home directory cannot be a shared volume or gpg-agent will fail to start
# since the socket name will be too long.

set -e

# Make any directories in case they are missing.
mkdir -p /root/sbt-gpg/target/.gnupg
mkdir -p /root/.gnupg

# Copy the files to the GnuPG home directory.
cp -R /root/sbt-gpg/target/.gnupg /root/

# Execute the command
$@

# Cleanup any remaining sockets.
pidof gpg-agent | xargs kill -9
rm -f /root/.gnupg/S.gpg-agent*

# Copy the files back to the target directory.
cp -R /root/.gnupg /root/sbt-gpg/target/
